### ISSUE TITLE
Download button 404s on https://madbitco.github.io/sketchflow/

### ISSUE THREAD

**Issue by franzheidl** [matthewmorek/Sketchflow#1]
When clicking the the large ”Download” button on https://madbitco.github.io/sketchflow/ I get an 404. The download link further down below the page works fine.

**Comment by matthewmorek** [comment]
@franzheidl Hey, thanks bringing it to our attention! I'll make sure this is fixed ASAP! 👍

**Comment by matthewmorek** [comment]
This was resolved in 0fa56a33565b7926d6c9697e7d7a8b65e091a812.
